(function(){
'use strict';
const C=PKCore, own=NEW_THINKING_BOOKS;
const el=document.createElement('section');el.id='s-pk';el.className='screen pk';document.body.appendChild(el);
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const h=escape;
let studyPool=[],studyOffset=0;
let session=null,activities=[],audio=null,utterance=null,audioEpoch=0,heard=false,busy=false,currentBook=null,studyWords=[],studyIndex=0,revealed=false;
const demo=!!window.PK_DEMO;
function user(){return G.user;}
function storageKey(){return 'word-pk-draft-v1:'+G.account;}
function readDraft(){try{return JSON.parse(localStorage.getItem(storageKey())||'null');}catch{return null;}}
function draft(){try{if(session)localStorage.setItem(storageKey(),JSON.stringify(session));}catch{}}
function clearDraft(){try{localStorage.removeItem(storageKey());}catch{}}
function records(){return Object.values(user().progress?.word_pk||{}).sort((a,b)=>(b.finishedAt||'').localeCompare(a.finishedAt||''));}
function reviews(){return user().progress?.word_pk_review||{};}
function allBooks(){
 const books=[...own];
 if(typeof BOOKS_CONFIG!=='undefined')for(const section of BOOKS_CONFIG)for(const b of section.books){
  if(b.locked||books.some(x=>x.id===b.id))continue;
  let data=b.wordData;
  if(!data&&b.quizMode==='irregular'){
   const verbs=b.id==='nce1_irregular'&&typeof NCE1_IRREGULAR!=='undefined'?NCE1_IRREGULAR:typeof NCE2_IRREGULAR!=='undefined'?NCE2_IRREGULAR:[];
   data={1:verbs.map(v=>({w:v.v1?.forms?.[0],m:'写出 '+v.v1?.forms?.[0]+' 的过去式',answer:v.v2?.forms?.[0],type:'verb',speech:v.v2?.forms?.[0]})).filter(v=>v.w&&v.answer)};
  }
  if(!data)continue;
  books.push({id:b.id,title:b.title,chapters:Object.entries(data).map(([number,words])=>({number,title:'单元 '+number,words:words.filter(w=>w.w&&w.m).map((w,i)=>({id:b.id+'-'+number+'-'+i,w:w.w,m:w.m,answer:w.answer||w.w,speech:w.speech||w.w,prompt:w.type==='verb'?w.m:w.m,type:w.type||(/\s/.test(w.w)?'phrase':'word'),hint:'先听发音，回忆词义，再遮住英文独立拼写。',bookId:b.id,chapter:number}))}))});
 }
 return books;
}
function stopAudio(){audioEpoch++;if(audio){audio.pause();audio=null;}if(window.speechSynthesis)window.speechSynthesis.cancel();utterance=null;busy=false;}
function display(content){stopAudio();el.innerHTML='<div class="shell">'+(demo?'<div class="demo">体验预览 · 使用虚拟学生，成绩仅保存在本机</div>':'')+'<div class="top"><div class="brand"><span class="brand-icon">W</span><div>梁老师的单词探险<small class="muted" style="display:block;font-size:11px">MORE THAN ENGLISH</small></div></div><div class="actions" style="margin:0"><span class="tag">'+h(user()?.name||'同学')+'</span><button data-act="home">活动大厅</button><button data-act="exit">返回课程</button></div></div>'+content+'<div class="footer">每天进步一点点，每个单词都算数。 · 梁老师趣味英语</div></div>';if(typeof scr==='function')scr('s-pk');else el.style.display='block';}
function button(act,label,cls='',extra=''){return '<button data-act="'+act+'" class="'+cls+'" '+extra+'>'+label+'</button>';}
function progressMeter(pct){return '<div class="meter"><div style="width:'+Math.max(0,Math.min(100,pct))+'%"></div></div>';}
function audioButtons(){return '<div class="actions">'+button('speak','🔊 听发音')+button('slow','🐢 慢速听')+'<span class="muted small" id="audio-status" role="status">点击播放 · 英语朗读</span></div>';}
function showHome(){
 const rs=records(),due=Object.values(reviews()).filter(x=>!x.done&&(!x.due||Date.parse(x.due)<=Date.now())).length;
 const best=Math.max(0,...rs.filter(r=>r.mode==='challenge').map(r=>r.levels||0));
 display('<section class="hero"><div><p class="eyebrow">WORD QUEST / 每一次尝试，都是进步</p><h1>今天，向下一关<br>再前进一步。</h1><p class="muted">带上 5 颗爱心，开启你的单词大 PK。<br>听一听、想一想、拼一拼，让单词变成你的好朋友。</p><div class="actions">'+button('setup','开始五心挑战 ↗','primary')+button('assessment','测测我的掌握情况')+'</div></div><div class="map" aria-label="闯关路线"><div class="island">🌱<small>出发</small></div><div class="island">🦜<small>动物岛</small></div><div class="island">🏝️<small>发现岛</small></div><div class="island">🎭<small>俱乐部</small></div><div class="island">🏆<small>下一关</small></div></div></section><div class="stats"><div class="stat"><strong>'+rs.length+'</strong><span>已完成练习 / 挑战</span></div><div class="stat"><strong>'+best+'</strong><span>个人最高通关数</span></div><div class="stat"><strong>'+due+'</strong><span>今天待复习条目</span></div></div>'+(readDraft()?'<div class="notice">你有一场尚未完成的挑战。 '+button('resume','继续上次挑战')+'</div>':'')+'<div class="section-line"><h2>我的新思维词书</h2><span class="muted">2 册 · 104 条 · 按原文章节</span></div><div class="grid">'+own.map((b,i)=>'<article class="card book"><div class="cover '+(i?'blue':'')+'"><small>NEW THINKING</small><strong>'+b.title.slice(-2)+'</strong></div><div><h3>'+h(b.title)+'</h3><p class="muted">'+b.chapters.map(c=>'Chapter '+c.number).join(' / ')+'<br>'+b.chapters.reduce((n,c)=>n+c.words.length,0)+' 条学习内容 · 情境记忆</p>'+button('book','打开词书 →','','data-book="'+b.id+'"')+'</div></article>').join('')+'</div><div class="section-line"><h2>把不会的，慢慢变成会的</h2></div><div class="grid"><div class="card"><h3>🔁 错词回访</h3><p class="muted">先回忆，再看提示。今天、明天、第 3 天、第 7 天，和老朋友再见一面。</p>'+button('review','去复习','soft')+'</div><div class="card"><h3>📊 我的成长记录</h3><p class="muted">分开查看认识词义、听音辨义和独立拼写。这里记录已测表现，不估算整体英语词汇量。</p>'+button('history','查看记录')+'</div></div>'+(activities.length?'<div class="section-line"><h2>老师的活动</h2></div><div class="grid">'+activities.map(a=>'<div class="card"><h3>'+h(a.title)+'</h3><p class="muted">5 颗爱心 · 连对 10 题晋级 · 个人练习挑战</p>'+button('activity','进入活动','primary','data-id="'+h(a.id)+'"')+'</div>').join('')+'</div>':''));
}
function showBook(id){currentBook=own.find(b=>b.id===id);if(!currentBook)return;display('<p class="eyebrow">YOUR WORD BOOK</p><h1>'+h(currentBook.title)+'</h1><p class="muted">按您提供的章节整理 · 每条都有记忆提示 · 短语与动词变化分别学习</p><div class="grid">'+currentBook.chapters.map(c=>'<div class="card"><span class="tag">'+c.words.length+' 条</span><h2>'+h(c.title)+'</h2><p class="muted">翻卡回忆 → 看提示 → 听发音 → 独立回想</p><div class="actions">'+button('study','趣味记忆','primary','data-chapter="'+c.number+'"')+button('chapterQuiz','章节闯关','','data-chapter="'+c.number+'"')+button('list','查看词表','','data-chapter="'+c.number+'"')+'</div></div>').join('')+'</div>');}
function showList(chapter){const words=currentBook.chapters.find(c=>String(c.number)===String(chapter)).words;studyWords=words;display('<h1>'+h(currentBook.title)+' · 词表</h1><p class="muted">点击喇叭试听。动词变化条目朗读过去式。固定音频为英式合成语音。</p><div class="word-list">'+words.map((w,i)=>'<div class="word-row"><div><strong>'+h(w.w)+'</strong><small>'+h(w.m)+'</small></div>'+button('listSpeak','🔊 朗读','','data-index="'+i+'"')+'</div>').join('')+'</div><p id="audio-status" role="status"></p>');}
function study(chapter,review=false){studyWords=review?C.pool(allBooks(),allBooks().map(b=>b.id)).filter(w=>{const r=reviews()[C.identity(w)];return r&&!r.done;}):currentBook.chapters.find(c=>String(c.number)===String(chapter)).words;studyPool=studyWords;studyOffset=0;studyWords=studyPool.slice(0,10);if(!studyWords.length){display('<div class="card center"><h2>暂时没有待复习条目 🌱</h2><p>完成挑战后，错词会自动来到这里。</p>'+button('home','返回大厅','primary')+'</div>');return;}studyIndex=0;revealed=false;renderStudy();}
function renderStudy(){const w=studyWords[studyIndex];display('<div class="question"><div class="row"><span class="tag">记忆卡 '+(studyIndex+1)+' / '+studyWords.length+'</span><span class="muted">先回想，再翻卡</span></div>'+progressMeter(studyIndex/studyWords.length*100)+'<div class="card"><p class="eyebrow">RECALL FIRST</p><div class="word">'+h(w.w)+'</div>'+audioButtons()+(revealed?'<div class="feedback"><strong>'+h(w.m)+'</strong><p class="hint">'+h(w.hint)+'</p></div>':'<p class="muted">它是什么意思？可以先说给自己听。</p>')+'<div class="actions">'+button('reveal',revealed?'遮住意思':'翻卡看记忆提示','soft')+button('studyNext',studyIndex+1===studyWords.length?'完成这组学习':'下一个 →','primary')+button('studyTest','本组无提示自测')+'</div></div><p class="muted small">翻卡不计入掌握量。完成后通过无提示答题检查记忆。</p></div>');}
function setup(mode='challenge',ids=null,chapter='',activity=null){
 const books=allBooks();display('<p class="eyebrow">'+(mode==='assessment'?'KNOW YOUR WORDS':'FIVE HEARTS CHALLENGE')+'</p><h1>'+(mode==='assessment'?'看看，你已经会了多少。':'准备好，向新纪录出发。')+'</h1><div class="grid"><div class="card"><h2>选择本次词库</h2><div class="checklist">'+books.map(b=>'<label><input type="checkbox" name="pk-book" value="'+h(b.id)+'" '+((ids||own.map(b=>b.id)).includes(b.id)?'checked':'')+'>'+h(b.title)+'</label>').join('')+'</div><div class="actions">'+button('selectAll','全选词书')+button('selectOwn','只选新思维')+'</div><label class="field">答题方式<select id="pk-kind"><option value="mixed">轮换挑战：词义 / 拼写 / 听音</option><option value="meaning">认识词义</option><option value="spell">独立拼写</option><option value="listen">听音辨义</option></select></label><div class="notice">'+(mode==='challenge'?'5 次错误机会；连对 10 题升一关。答错只清空当前连击。最后不足 10 题的连续正确尾关也计一关。':'没有爱心淘汰，逐条检查所选词库，可中途保存。仅报告已测表现，未测不代表不会。')+'</div>'+button('begin','开始'+(mode==='assessment'?'测评':'挑战'),'primary')+'<p id="setup-error" role="alert"></p></div><div class="card"><h2>每一步，都值得奖励</h2><p>🌱 1 关 · 单词新星</p><p>🧭 3 关 · 探索者</p><p>⚡ 5 关 · 挑战者</p><p>💎 8 关 · 单词大师</p><p>🏆 10 关 · 单词冠军</p><p class="muted">这是游戏等级。选择不同词库时，成绩不直接比较。短语与动词变化作为独立学习条目。</p><p class="muted small">新思维使用固定英式合成音频；其他词书使用设备英语朗读。声音不可用时不会扣心，可保存进度。</p></div></div>');
 if(chapter){const note=document.createElement('p');note.className='notice';note.textContent='本次限定 Chapter '+chapter+'，更换词书将切换为整本词书范围。';el.querySelector('.checklist').before(note);el.querySelectorAll('[name=pk-book]').forEach(x=>x.addEventListener('change',()=>{el.dataset.chapter='';note.remove();}));}
 el.dataset.mode=mode;el.dataset.chapter=chapter;el.dataset.activity=activity?.id||'';
}
function begin(){const ids=[...el.querySelectorAll('[name=pk-book]:checked')].map(x=>x.value);const chapter=el.dataset.chapter;const words=C.pool(allBooks(),ids,chapter);if(!words.length){el.querySelector('#setup-error').textContent='请至少选择一本有内容的词书。';return;}const a=activities.find(x=>x.id===el.dataset.activity);session=C.create(words,el.dataset.mode,el.querySelector('#pk-kind').value,{bookIds:ids,chapter,activityId:a?.id||'',activityTitle:a?.title||''});draft();renderQuestion();}
function renderQuestion(){
 if(session.finished){finish();return;}heard=false;
 const w=session.words[session.index],kind=C.questionKind(session),answered=session.answered;
 display('<div class="question"><div class="row"><span class="tag">'+(session.mode==='assessment'?'词汇测评':'第 '+(session.levels+1)+' 关')+' · 第 '+(session.index+1)+' / '+session.words.length+' 题</span>'+(session.mode==='challenge'?'<span class="hearts" aria-label="剩余 '+session.lives+' 颗爱心">'+'♥'.repeat(session.lives)+'♡'.repeat(5-session.lives)+'</span>':'<span class="muted">安心作答，没有淘汰</span>')+'</div>'+progressMeter(session.answers.length/session.words.length*100)+'<div class="card"><div class="row"><p class="eyebrow">'+({meaning:'认识词义',spell:'独立拼写',listen:'听音辨义'})[kind]+'</p><span class="tag">连对 '+session.streak+' 题</span></div><div class="word">'+(kind==='listen'?'🎧 听一听，选出意思':h(kind==='spell'?w.prompt:w.w))+'</div><p class="muted">'+(kind==='spell'?'在下面输入英文答案。大小写与句末标点不影响判断。':kind==='listen'?'先完整听一遍，再选择中文意思。':'选出正确的中文意思。')+'</p>'+(kind==='listen'||kind==='meaning'?audioButtons():'')+(kind==='spell'?'<form id="pk-answer" class="spell"><input aria-label="英文答案" id="pk-spelling" autocomplete="off" autocapitalize="off" spellcheck="false" '+(answered?'disabled':'')+'><button class="primary" '+(answered?'disabled':'')+'>确认答案</button></form>':'<div class="choices">'+C.options(w,session.words,kind).map(v=>button('answer',h(v),'','data-value="'+h(v)+'" '+(answered||kind==='listen'?'disabled':''))).join('')+'</div>')+'<div id="pk-feedback" role="status" aria-live="polite"></div><div class="actions">'+button('next','下一题 →','primary','hidden')+'</div></div><div class="actions">'+button('pause','保存进度，稍后继续')+'</div><p class="muted small">'+(kind==='spell'&&w.type==='verb'?'本题检查动词过去式。':'每条仅计一次；错词进入复习，不重复增加成绩。')+'</p></div>');
 if(answered)feedback(session.answers.at(-1).ok,true);
 const form=el.querySelector('#pk-answer');if(form)form.addEventListener('submit',e=>{e.preventDefault();submit(el.querySelector('#pk-spelling').value);});
 if(kind==='spell'&&!answered)el.querySelector('#pk-spelling').focus();
}
function feedback(ok,restored=false){const w=session.words[session.index];const box=el.querySelector('#pk-feedback');box.className='feedback'+(ok?'':' wrong');box.innerHTML=(ok?'✓ 答对了！继续向前。':'再记一次，下次会更熟悉。')+'<br><strong>'+h(w.w)+'</strong> · '+h(w.m)+(session.mode==='challenge'&&session.streak&&session.streak%10===0?'<br>🎉 连对 10 题，成功升一关！':'')+(ok?'':'<p class="hint">'+h(w.hint)+'</p>')+'<div class="actions">'+button('answerAudio','🔊 听正确发音')+'</div>';el.querySelectorAll('.choices button,#pk-answer input,#pk-answer button').forEach(b=>b.disabled=true);const n=el.querySelector('[data-act=next]');n.hidden=false;n.textContent=session.finished||session.index===session.words.length-1?'查看结果':'下一题 →';if(!restored)draft();}
function submit(value){if(!value.trim())return;const ok=C.answer(session,value,heard);if(ok===null)return;stopAudio();feedback(ok);const hearts=el.querySelector('.hearts');if(hearts){hearts.textContent='♥'.repeat(session.lives)+'♡'.repeat(5-session.lives);hearts.setAttribute('aria-label','剩余 '+session.lives+' 颗爱心');}draft();}
function addReview(r){const p=user().progress;const bank=p.word_pk_review||(p.word_pk_review={});for(const a of r.answers){let item=bank[a.key];if(!a.ok){bank[a.key]={id:a.id,w:a.w,m:a.m,done:false,pct:0,stage:0,lastDay:'',updatedAt:new Date().toISOString(),due:new Date().toISOString()};}else if(item&&!item.done){const now=new Date();const today=now.getFullYear()+'-'+(now.getMonth()+1)+'-'+now.getDate();if(item.lastDay!==today){item.updatedAt=new Date().toISOString();item.stage=(item.stage||0)+1;item.lastDay=today;item.done=item.stage>=3;item.pct=Math.min(100,Math.round(item.stage/3*100));item.due=new Date(Date.now()+[1,3,7][Math.min(item.stage-1,2)]*86400000).toISOString();}}}}

function updateBookProgress(r){
 for(const b of own){for(const ch of b.chapters){const answers=r.answers.filter(a=>ch.words.some(w=>w.id===a.id));if(!answers.length)continue;const bp=user().progress[b.id]||(user().progress[b.id]={});const prev=bp[ch.number]||{};const evidence={...(prev.evidence||{})};for(const a of answers)evidence[a.id]=a.ok;const count=ch.words.filter(w=>evidence[w.id]===true).length;bp[ch.number]={done:count===ch.words.length,pct:Math.round(count/ch.words.length*100),updatedAt:new Date().toISOString(),evidence};}}
}

async function saveResult(r){user().progress=user().progress||{};const p=user().progress.word_pk||(user().progress.word_pk={});if(!p[r.id]){p[r.id]=r;addReview(r);updateBookProgress(r);const keys=Object.keys(p);while(keys.length>100)delete p[keys.shift()];}
 try{await saveProg();return demo?'体验成绩已保存在本机。':G.cloudToken?'已提交云端同步；老师可在后台查看练习记录。':'已保存在本机，尚未同步云端。';}catch{const saved=window.loveWordsCloud?.localRead(G.account)?.progress?.word_pk?.[r.id];return saved?'已保存在本机，云端同步失败。请联网后点击重试同步。':'保存尚未完成，请点击重试同步。暂时不要关闭页面。';}}
async function finish(){
 const r=C.report(session);display('<div class="question center"><div class="medal">'+(r.mode==='assessment'?'📊':'🏅')+'</div><p class="eyebrow">EVERY STEP COUNTS</p><h1>'+h(r.mode==='assessment'?'你的词汇观察报告':C.badge(r.levels))+'</h1><p class="muted">'+(r.lives===0?'五颗爱心用完了，带上新收获，下次再出发。':'完成本次内容！让今天学会的，成为明天熟悉的。')+'</p><div class="stats"><div class="stat"><strong>'+r.correct+'</strong><span>答对条目</span></div><div class="stat"><strong>'+r.maxStreak+'</strong><span>最长连对</span></div><div class="stat"><strong>'+r.levels+'</strong><span>通过关卡</span></div></div><div class="card" style="text-align:left"><h2>我会什么，还要练什么</h2>'+Object.entries(r.skills).map(([k,v])=>'<div class="row"><span>'+({meaning:'认识词义',listen:'听音辨义',spell:'独立拼写'})[k]+'</span><strong>'+(v.total?v.correct+' / '+v.total:'本次未测')+'</strong></div>'+progressMeter(v.total?v.correct/v.total*100:0)).join('')+'<p class="muted">本次测试 '+r.tested+' / '+r.total+' 条；未测 '+r.unseen+' 条。单次作答不代表稳定掌握，不换算整体英语词汇量。</p><p class="muted">'+['word','phrase','verb'].map(t=>({word:'单词',phrase:'短语',verb:'动词变化'})[t]+' '+r.answers.filter(a=>a.type===t).length+' 条').join(' · ')+'</p></div><p id="pk-save-status" role="status">正在保存…</p><div class="actions">'+button('retrySync','重试同步')+button('review','复习错词','soft')+button('home','返回大厅','primary')+'</div></div>');
 const status=await saveResult(r);if(!status.startsWith('保存尚未完成'))clearDraft();const msg=el.querySelector('#pk-save-status');if(msg)msg.textContent=status;
}
function history(){const rs=records();display('<h1>我的成长记录</h1><p class="muted">不同词库和题型的成绩不直接比较。最多保留最近 100 场记录。</p><div class="card table-scroll"><table><thead><tr><th>时间</th><th>练习范围</th><th>模式</th><th>正确 / 已测</th><th>关卡</th><th>最长连对</th></tr></thead><tbody>'+rs.map(r=>'<tr><td>'+h(new Date(r.finishedAt).toLocaleString())+'</td><td>'+h(r.bookIds.map(id=>allBooks().find(b=>b.id===id)?.title||id).join('、'))+'</td><td>'+h(r.mode==='assessment'?'测评':'闯关')+'</td><td>'+r.correct+' / '+r.tested+'</td><td>'+r.levels+'</td><td>'+r.maxStreak+'</td></tr>').join('')+'</tbody></table>'+(!rs.length?'<p>你的第一场挑战正在等你。</p>':'')+'</div>');}
async function speak(w,slow=false){
 stopAudio();const epoch=audioEpoch;busy=true;const msg=el.querySelector('#audio-status');if(msg)msg.textContent='正在准备声音…';
 function end(ok){if(epoch!==audioEpoch)return;busy=false;if(ok){heard=true;if(msg)msg.textContent='已播放，可再次点击重听。';if(session&&!session.answered)el.querySelectorAll('.choices button').forEach(b=>b.disabled=false);}else{if(msg)msg.textContent='声音暂不可用，请重试或保存进度；不会扣心。';}}
 if(w.audio){try{audio=new Audio(w.audio);audio.playbackRate=slow?.75:1;audio.preservesPitch=true;audio.onended=()=>end(true);audio.onerror=()=>end(false);const timeout=setTimeout(()=>{if(epoch===audioEpoch&&busy){audio?.pause();end(false);}},18000);audio.addEventListener('ended',()=>clearTimeout(timeout),{once:true});await audio.play();return;}catch{end(false);return;}}
 if(!window.speechSynthesis){end(false);return;}const voices=window.speechSynthesis.getVoices();const voice=voices.find(v=>v.lang==='en-GB')||voices.find(v=>v.lang.startsWith('en'));if(!voice){end(false);return;}
 utterance=new SpeechSynthesisUtterance(w.speech||w.answer||w.w);utterance.voice=voice;utterance.lang=voice.lang;utterance.rate=slow?.65:.85;utterance.onend=()=>end(true);utterance.onerror=()=>end(false);window.speechSynthesis.speak(utterance);setTimeout(()=>{if(epoch===audioEpoch&&busy){window.speechSynthesis.cancel();end(false);}},18000);
}
function activeWord(){return el.querySelector('[data-act=studyNext]')?studyWords[studyIndex]:session?.words[session.index];}
el.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b||b.disabled)return;const a=b.dataset.act;
 if(a==='home')showHome();else if(a==='exit'){stopAudio();showBooks();}else if(a==='book')showBook(b.dataset.book);else if(a==='list')showList(b.dataset.chapter);else if(a==='listSpeak')speak(studyWords[+b.dataset.index]);else if(a==='study')study(b.dataset.chapter);else if(a==='review')study(null,true);else if(a==='reveal'){revealed=!revealed;renderStudy();}else if(a==='studyNext'){if(++studyIndex>=studyWords.length){display('<div class="card center"><h1>这一组，已经认识啦！🌱</h1><p>接下来不看提示答题，看看记住了多少。</p>'+button('studyTest','本组无提示自测','primary')+(studyOffset+10<studyPool.length?button('studyMore','继续下一组记忆卡'):'')+'</div>');}else{revealed=false;renderStudy();}}else if(a==='studyTest'){session=C.create(studyWords,'assessment','mixed',{bookIds:[...new Set(studyWords.map(w=>w.bookId))]});draft();renderQuestion();}else if(a==='studyMore'){studyOffset+=10;studyWords=studyPool.slice(studyOffset,studyOffset+10);studyIndex=0;revealed=false;renderStudy();}else if(a==='setup')setup();else if(a==='assessment')setup('assessment');else if(a==='chapterQuiz')setup('challenge',[currentBook.id],b.dataset.chapter);else if(a==='selectAll'||a==='selectOwn'){el.dataset.chapter='';el.querySelectorAll('[name=pk-book]').forEach(x=>x.checked=a==='selectAll'||own.some(b=>b.id===x.value));}else if(a==='activity'){const act=activities.find(x=>x.id===b.dataset.id);setup('challenge',act.bookIds,'',act);}else if(a==='begin')begin();else if(a==='answer')submit(b.dataset.value);else if(a==='next'){if(!session.finished)C.next(session);draft();renderQuestion();}else if(a==='pause'){draft();showHome();}else if(a==='resume'){session=readDraft();if(session)renderQuestion();}else if(a==='history')history();else if(a==='speak'||a==='slow'||a==='answerAudio'){const w=activeWord();if(w)speak(w,a==='slow');}else if(a==='retrySync'&&session)saveResult(C.report(session)).then(s=>{const msg=el.querySelector('#pk-save-status');if(msg)msg.textContent=s;});
});
window.PKApp={open:showHome,openBook:showBook};
if(typeof BOOKS_CONFIG!=='undefined'){
 BOOKS_CONFIG.unshift({section:'🌱 新思维英语',books:own.map(b=>({id:b.id,title:b.title,icon:b.icon,desc:b.chapters.map(c=>'Chapter '+c.number).join(' / ')+' · '+b.chapters.reduce((n,c)=>n+c.words.length,0)+' 条 · 情境记忆与闯关',units:b.chapters.length,badge:'新上线',badgeCls:'avail',pkBook:true}))});
 const previousSelect=window.selectBook;window.selectBook=function(b){if(b.pkBook)showBook(b.id);else previousSelect(b);};
 const previousRender=window.renderBooks;window.renderBooks=function(){previousRender();const wrap=document.getElementById('book-grid-wrap');const entry=document.createElement('button');entry.className='pk-entry';entry.innerHTML='<div><strong>🌱 单词大 PK · 五心挑战</strong><span>两册新思维 · 全词书挑战 · 看见每一点进步</span></div><b>开始探险 ↗</b>';entry.onclick=showHome;wrap.prepend(entry);};
}
fetch('data/pk-activities.json',{cache:'no-cache'}).then(r=>r.ok?r.json():null).then(x=>{activities=(x?.activities||[]).filter(a=>a.published);if(demo&&!session)showHome();}).catch(()=>{});
window.addEventListener('beforeunload',()=>{if(session&&!session.finished)draft();});
if(demo)showHome();
})();
