(function(){
'use strict';
const books=NEW_THINKING_BOOKS,root=document.createElement('section');root.className='pk pk-admin';root.id='pk-teacher';document.getElementById('main').append(root);
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let activities=[],selectedAudio=null;
for(const b of books)BOOKS[b.id]=b.title;BOOKS.word_pk='单词大 PK';BOOKS.word_pk_review='单词复习';
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function activityList(){return activities.map((a,i)=>'<div class="word-row"><div><strong>'+h(a.title)+'</strong><small>'+a.bookIds.map(id=>h(BOOKS[id]||id)).join('、')+' · '+(a.published?'将在发布后开放':'将在发布后下架')+'</small></div><button data-act="toggle" data-index="'+i+'">'+(a.published?'设为下架':'设为开放')+'</button></div>').join('');}
function reports(){return (typeof data!=='undefined'?data:[]).flatMap(s=>Object.values((s.learning||{}).progress?.word_pk||{}).map(r=>({...r,student:s.name,account:s.account,cls:s.cls}))).sort((a,b)=>(b.finishedAt||'').localeCompare(a.finishedAt||''));}
function renderPK(){
 const rs=reports();root.innerHTML='<div class="card"><p class="eyebrow">NEW THINKING / 词书与活动</p><h2>新思维词书 · 单词大 PK</h2><p class="muted">Book 4A 46 条，Book 4B 58 条。词书随本次网页版本发布；下方活动设置需导出并更新到网站后才对学生生效。</p><div class="grid">'+books.map(b=>'<div><h3>'+h(b.title)+'</h3><p class="muted">'+b.chapters.map(c=>'Chapter '+c.number).join(' / ')+'</p><button data-act="preview" data-id="'+b.id+'">预览词条与试听音频</button></div>').join('')+'</div><div id="pk-audio-preview"></div></div><div class="card"><h2>活动设置</h2><p class="notice">这里编辑的是待发布配置。点击“导出活动配置”得到 pk-activities.json，将它替换到 GitHub 项目的 data 文件夹后生效。当前未接入后台一键发布服务。</p><label class="field">活动名称<input id="pk-activity-title" maxlength="60" placeholder="例如：四年级周五单词挑战"></label><div class="checklist">'+books.map(b=>'<label><input name="teacher-book" type="checkbox" value="'+b.id+'" checked>'+h(b.title)+'</label>').join('')+'</div><p class="muted">本版固定：5 颗爱心，连对 10 题晋级。活动面向现有学生账号；不设正式排名。</p><div class="actions"><button data-act="add" class="primary">添加活动草稿</button><button data-act="export">导出活动配置</button></div><p id="pk-admin-status" role="status"></p><div id="pk-activity-list" class="word-list">'+activityList()+'</div></div><div class="card"><div class="row"><h2>学生 PK 与测评记录</h2><button data-act="csv">导出比赛记录 CSV</button></div><p class="muted">来自已有成绩同步服务；本版是学生端计算的练习记录，尚不具备服务端计分校验，不用于正式竞赛排名。</p><label class="field">筛选姓名、账号或班级<input id="pk-report-search" type="search" placeholder="输入关键词"></label><div id="pk-report-table"></div></div>';
 renderReportTable(rs);
}
function renderReportTable(rs){root.querySelector('#pk-report-table').innerHTML='<div class="table-scroll"><table><thead><tr><th>学生</th><th>活动 / 范围</th><th>模式</th><th>正确 / 已测</th><th>词义 / 听音 / 拼写</th><th>关卡 / 连击</th><th>待复习条目</th><th>时间</th></tr></thead><tbody>'+rs.map(r=>'<tr><td>'+h(r.student)+'<br>'+h(r.cls)+'</td><td>'+h(r.activityTitle||r.bookIds?.map(id=>BOOKS[id]||id).join('、')||'自主练习')+'</td><td>'+(r.mode==='assessment'?'测评':'闯关')+'</td><td>'+h(r.correct)+' / '+h(r.tested)+'</td><td>'+['meaning','listen','spell'].map(k=>{const s=r.skills?.[k];return s?.total?s.correct+'/'+s.total:'未测';}).join(' · ')+'</td><td>'+h(r.levels)+' / '+h(r.maxStreak)+'</td><td><details><summary>'+((r.answers||[]).filter(a=>!a.ok).length)+' 条</summary>'+((r.answers||[]).filter(a=>!a.ok).map(a=>h(a.w)+' · '+h(a.m)).join('<br>')||'本场全对')+'</details></td><td>'+h(new Date(r.finishedAt).toLocaleString())+'</td></tr>').join('')+'</tbody></table></div>'+(!rs.length?'<p class="muted">暂无同步记录。学生完成挑战并成功同步后，点击原后台的“刷新”查看。</p>':'');}
root.addEventListener('input',e=>{if(e.target.id==='pk-report-search'){const q=e.target.value.trim().toLowerCase();renderReportTable(reports().filter(r=>[r.student,r.account,r.cls].join(' ').toLowerCase().includes(q)));}});
root.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const act=b.dataset.act;
 if(act==='preview'){const book=books.find(x=>x.id===b.dataset.id);root.querySelector('#pk-audio-preview').innerHTML='<div class="notice">固定音频：英式合成语音 Daniel。请试听确认教材读法，尤其是专有名词和动词变化。未将合成音频标为人工校对通过。</div><div class="word-list">'+book.chapters.flatMap(c=>c.words.map(w=>'<div class="word-row"><div><strong>'+h(w.w)+'</strong> · '+h(w.m)+'<small>Chapter '+c.number+' · '+h(w.hint)+'</small></div><button data-act="audio" data-path="'+h(w.audio)+'">🔊 试听</button></div>')).join('')+'</div>';}
 else if(act==='audio'){selectedAudio?.pause();selectedAudio=new Audio(b.dataset.path);selectedAudio.play().catch(()=>{b.textContent='加载失败，点击重试';});}
 else if(act==='add'){const title=root.querySelector('#pk-activity-title').value.trim(),ids=[...root.querySelectorAll('[name=teacher-book]:checked')].map(x=>x.value);if(!title||!ids.length){root.querySelector('#pk-admin-status').textContent='请填写活动名称，并选择至少一本词书。';return;}activities.push({id:'activity-'+Date.now().toString(36),title,bookIds:ids,lives:5,streakGoal:10,published:true});root.querySelector('#pk-activity-list').innerHTML=activityList();root.querySelector('#pk-admin-status').textContent='已加入本页草稿，尚未发布。请导出后更新到网站。';}
 else if(act==='toggle'){activities[+b.dataset.index].published=!activities[+b.dataset.index].published;root.querySelector('#pk-activity-list').innerHTML=activityList();root.querySelector('#pk-admin-status').textContent='配置已修改，尚未发布。';}
 else if(act==='export'){download('pk-activities.json',JSON.stringify({version:1,activities},null,2),'application/json');root.querySelector('#pk-admin-status').textContent='已导出，请替换 GitHub 项目中的 data/pk-activities.json。';}
 else if(act==='csv'){const lines=[['学生','账号','班级','时间','模式','词书','正确','已测','未测','关卡','最长连对'],...reports().map(r=>[r.student,r.account,r.cls,r.finishedAt,r.mode,r.bookIds?.join(' / '),r.correct,r.tested,r.unseen,r.levels,r.maxStreak])];const csv='\ufeff'+lines.map(row=>row.map(v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(',')).join('\r\n');download('单词PK练习记录.csv',csv,'text/csv;charset=utf-8');}
});
const previousRender=window.render;window.render=function(){const select=document.getElementById('book');[...select.options].filter(o=>o.value==='word_pk'||o.value==='word_pk_review').forEach(o=>o.remove());previousRender();renderPK();};
const previousStats=window.stats;window.stats=function(s){const copy={...s,learning:{...(s.learning||{}),progress:{...((s.learning||{}).progress||{})}}};delete copy.learning.progress.word_pk;delete copy.learning.progress.word_pk_review;return previousStats(copy);};
fetch('data/pk-activities.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(x=>{activities=x.activities||[];renderPK();}).catch(()=>{renderPK();root.querySelector('#pk-admin-status').textContent='活动配置未能读取，请刷新后再编辑，避免覆盖现有活动。';root.querySelectorAll('[data-act=export],[data-act=add]').forEach(b=>b.disabled=true);});
renderPK();
})();
