/* Pure rules shared by the application and regression tests. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.PKCore=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const normalize=s=>String(s||'').normalize('NFKC').toLowerCase().trim().replace(/[’‘]/g,"'").replace(/[.!?]+$/g,'').replace(/\s+/g,' ');
function identity(w){return normalize(w.answer||w.w)+'|'+normalize(w.m)+'|'+(w.type||'word');}
function pool(books,ids,chapter){const map=new Map();for(const b of books.filter(b=>ids.includes(b.id)))for(const c of b.chapters)if(!chapter||String(c.number)===String(chapter))for(const w of c.words){const k=identity(w);if(map.has(k)){const item=map.get(k);item.sources.push({bookId:b.id,chapter:c.number});}else map.set(k,{...w,sources:[{bookId:b.id,chapter:c.number}]});}return [...map.values()];}
function shuffle(a,random=Math.random){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function create(words,mode='challenge',kind='mixed',options={}){return {id:options.id||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),version:1,mode,kind,words:shuffle(words),index:0,lives:5,streak:0,maxStreak:0,levels:0,correct:0,answers:[],answered:false,finished:words.length===0,startedAt:new Date().toISOString(),...options};}
function questionKind(s){if(s.kind!=='mixed')return s.kind;return ['meaning','spell','listen'][s.index%3];}
function answer(s,value,heard=true){if(s.finished||s.answered)return null;const w=s.words[s.index],kind=questionKind(s);if(kind==='listen'&&!heard)return null;const ok=normalize(value)===normalize(kind==='meaning'||kind==='listen'?w.m:w.answer);s.answered=true;s.correct+=ok?1:0;s.streak=ok?s.streak+1:0;s.maxStreak=Math.max(s.maxStreak,s.streak);if(s.mode==='challenge'){if(!ok)s.lives--;if(ok&&s.streak%10===0)s.levels++;}s.answers.push({id:w.id,key:identity(w),w:w.w,m:w.m,type:w.type,kind,ok,at:new Date().toISOString()});if(s.mode==='challenge'&&s.lives===0)s.finished=true;return ok;}
function next(s){if(!s.answered||s.finished)return false;s.index++;s.answered=false;if(s.index>=s.words.length){s.finished=true;if(s.mode==='challenge'&&s.streak%10>0)s.levels++;}return true;}
function report(s){const skills={meaning:{total:0,correct:0},listen:{total:0,correct:0},spell:{total:0,correct:0}};for(const a of s.answers){skills[a.kind].total++;skills[a.kind].correct+=a.ok?1:0;}return {id:s.id,mode:s.mode,kind:s.kind,bookIds:s.bookIds||[],chapter:s.chapter||'',activityId:s.activityId||'',activityTitle:s.activityTitle||'',done:!!s.finished,pct:s.answers.length?Math.round(s.correct/s.answers.length*100):0,correct:s.correct,tested:s.answers.length,total:s.words.length,unseen:s.words.length-s.answers.length,lives:s.lives,levels:s.levels,maxStreak:s.maxStreak,skills,answers:s.answers,finishedAt:new Date().toISOString(),version:s.version};}
function badge(level){return level>=10?'单词冠军':level>=8?'单词大师':level>=5?'挑战者':level>=3?'探索者':level>=1?'单词新星':'勇敢出发';}
function options(w,words,kind){const value=kind==='spell'?w.answer:w.m;const other=[...new Set(words.map(x=>kind==='spell'?x.answer:x.m))].filter(x=>normalize(x)!==normalize(value));return shuffle([value,...shuffle(other).slice(0,3)]);}
return {normalize,identity,pool,shuffle,create,questionKind,answer,next,report,badge,options};
});
